name: Rspec

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Build and test with RSpec
      env:
        CLASSROOM_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        result=$(sh grader.sh)
        curl https://api.github.com/repos/d12/graphql-remote_loader
        echo $result
        echo $CLASSROOM_TOKEN
   
